theme: minima
title: Catholic Good News
author: catholicgoodnws
email: catholicgoodnws@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Spread the good news from the Catholic Bible.

# social links
twitter_username: catholicgoodnws # DO NOT include the @ character, or else the build will fail!
github_username:  catholicgoodnws # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
